name: grocery_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.3
  http: ^1.2.2
  shared_preferences: ^2.1.0
  intl: ^0.17.0


  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  convex_bottom_bar: ^3.0.0
  font_awesome_flutter: ^10.1.0
  flutter_lints: ^4.0.0
  image_picker: ^1.0.0+1
  razorpay_flutter: ^1.3.6
  qr_flutter: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/cities.json
